---
title: "Isolate_Categories"
author: "Hannah Whitehurst"
date: "11/7/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
library(shiny)
libray(dplyr)
library(magrittr)
knitr::opts_chunk$set(echo = TRUE)


```

## Bergelson Lab Isolate Inventory

This project aims to summarize bacterial isolates on hand, and cross-tabulate the specimen with their associated projects.


```{r eruptions, echo=FALSE}
iso_df <- read.csv("/Users/hannahwhitehurst/Documents/Isolate_Docs/FH-HK-HW.csv")

iso_df_gen <- as.character(unique(iso_df$Genus))

unique()
selectInput(
  'Genus', label = 'genus',
  choices = c(iso_df_gen), 
  selected = 'Sphingomonas',
  multiple = TRUE
)

renderPlot({
  par(mar = c(4, 4, .1, .5))
  hist(
    faithful$eruptions, as.numeric(input$breaks),
    col = 'gray', border = 'white',
    xlab = 'Duration (minutes)', main = ''
  )
})

server = function(input, output) {
    output$data <- renderTable({
      iso_df[, c(input$Genus), drop = FALSE]
    }, rownames = TRUE)
  }

#######
iso_df_gen <- as.character(unique(iso_df$Genus))

shinyApp(
  ui = fluidPage(

    selectInput(
   'Genus', label = 'genus',
    choices = c(iso_df_gen), 
    selected = 'Sphingomonas',
    multiple = TRUE),
    plotOutput("Plot"),
    tableOutput("data")

  ),
  server = function(input, output) {
  
  filtered_data <- reactive({
   df <- iso_df[iso_df[, "Genus"] == input$Genus,] #ok
   df <- df[,c("Genus","population.site")] %>% #ok 
         droplevels() %>% #ok
          table() %>% #ok
         data.frame() #ok
   df <- df[with(df, order(Genus)),] #ok
  
  }
  )
  
  output$Plot <- renderPlot({
   g<-ggplot(data=filtered_data(), aes(y=Genus, x=Freq)) +
        geom_col(aes(fill=population.site))
   g
   }
   )
    
  output$data <- renderTable({
  iso_df[iso_df[, "Genus"] == input$Genus,]
  }, rownames = TRUE)
  
  

  


}
)
``` 


